auto_accept: True
interface: 0.0.0.0
publish_port: 4505
ret_port: 4506
user: root
file_root: /srv/salt
pillar_root: /srv/pillar
log_level: debug
log_file: /var/log/salt/master
key_logfile: /var/log/salt/key

### Vagrants `grains_config` puts it here.
include:
  - /etc/salt/grains
